# Generated by Django 4.2.1 on 2023-05-29 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_blog_author_alter_blog_published_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogAuthor',
        ),
    ]
