# Generated by Django 4.2.1 on 2023-06-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_delete_blogauthor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Published_at'),
        ),
    ]
