# Generated by Django 4.2.1 on 2023-05-21 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactInfo',
        ),
    ]
