# Generated by Django 4.2.1 on 2023-05-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_contactus_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostumEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costum_email', models.EmailField(max_length=100, verbose_name='Costum email')),
                ('your_choice', models.BooleanField(default=False, verbose_name='Your choice')),
            ],
            options={
                'verbose_name': 'Costum Email',
                'verbose_name_plural': 'Costum Emails',
            },
        ),
    ]
