# Generated by Django 4.2.1 on 2023-05-27 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_costumemail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CostumEmail',
        ),
    ]
