# Generated by Django 4.2.1 on 2023-05-08 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmegencyCases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_title', models.CharField(blank=True, max_length=250, verbose_name='hTitle')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('content', models.TextField(blank=True, verbose_name='Content')),
            ],
            options={
                'verbose_name': 'EmegencyCases',
                'verbose_name_plural': 'EmegencyCases',
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lil_title', models.CharField(blank=True, max_length=250, verbose_name='lTitle')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('content', models.TextField(blank=True, verbose_name='Content')),
                ('link_content', models.TextField(blank=True, verbose_name='lContent')),
            ],
            options={
                'verbose_name': 'HomePage',
                'verbose_name_plural': 'HomePage',
            },
        ),
        migrations.CreateModel(
            name='OnlineAppoinment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_title', models.CharField(blank=True, max_length=250, verbose_name='hTitle')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('content', models.TextField(blank=True, verbose_name='Content')),
                ('link_content', models.TextField(blank=True, verbose_name='lContent')),
            ],
            options={
                'verbose_name': 'OnlineAppoinment',
                'verbose_name_plural': 'OnlineAppoinment',
            },
        ),
        migrations.CreateModel(
            name='PersonalCare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('content', models.TextField(blank=True, verbose_name='Content')),
                ('link_content', models.TextField(blank=True, verbose_name='lContent')),
            ],
            options={
                'verbose_name': 'PersonalCare',
                'verbose_name_plural': 'PersonalCare',
            },
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('content', models.TextField(blank=True, verbose_name='Content')),
            ],
            options={
                'verbose_name': 'WorkingHours',
                'verbose_name_plural': 'WorkingHours',
            },
        ),
        migrations.CreateModel(
            name='WorkingHoursPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('content', models.TextField(blank=True, verbose_name='Content')),
                ('workingh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points', to='core.workinghours')),
            ],
            options={
                'verbose_name': 'WorkingHoursPoint',
                'verbose_name_plural': 'WorkingHoursPoints',
            },
        ),
    ]
