# Generated by Django 4.2.1 on 2023-05-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_workinghours_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.ImageField(default='default_image.png', upload_to='About', verbose_name='Image'),
        ),
    ]
