# Generated by Django 4.2.1 on 2023-05-09 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_courses_delete_emegencycases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='content',
        ),
        migrations.CreateModel(
            name='CoursesPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('courses', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cou_points', to='core.courses')),
            ],
            options={
                'verbose_name': 'CoursesPoint',
                'verbose_name_plural': 'CoursesPoint',
            },
        ),
    ]
