# Generated by Django 4.2.1 on 2023-05-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_courses_content_coursespoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursespoint',
            name='url',
            field=models.CharField(default='salam', max_length=50, verbose_name='Url'),
        ),
    ]
