# Generated by Django 4.2.1 on 2023-05-09 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_coursespoint_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Resources',
                'verbose_name_plural': 'Resources',
            },
        ),
        migrations.CreateModel(
            name='ResourcesPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('url', models.CharField(default='salam', max_length=50, verbose_name='Url')),
                ('resources', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='res_points', to='core.resources')),
            ],
            options={
                'verbose_name': 'ResourcesPoint',
                'verbose_name_plural': 'ResourcesPoint',
            },
        ),
        migrations.DeleteModel(
            name='PersonalCare',
        ),
    ]
