# Generated by Django 4.2.1 on 2023-05-10 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_resources_resourcespoint_delete_personalcare'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetInTouch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'GetInTouch',
                'verbose_name_plural': 'GetInTouch',
            },
        ),
        migrations.AlterField(
            model_name='resourcespoint',
            name='url',
            field=models.CharField(default='/', max_length=50, verbose_name='Url'),
        ),
        migrations.CreateModel(
            name='GetInTouchPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('url', models.CharField(default='/', max_length=50, verbose_name='Url')),
                ('getintouch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_points', to='core.getintouch')),
            ],
            options={
                'verbose_name': 'GetInTouchPoint',
                'verbose_name_plural': 'GetInTouchPoint',
            },
        ),
    ]
