# Generated by Django 4.2.1 on 2023-05-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_getintouch_alter_resourcespoint_url_getintouchpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='getintouchpoint',
            name='clas',
            field=models.CharField(default='', max_length=50, verbose_name='Class'),
        ),
    ]
