# Generated by Django 4.2.1 on 2023-05-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_getintouchpoint_clas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getintouchpoint',
            name='url',
            field=models.CharField(default='/', max_length=120, verbose_name='Url'),
        ),
    ]
