# Generated by Django 4.2.1 on 2023-05-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_getintouchpoint_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=100)),
                ('logo', models.ImageField(upload_to='About')),
                ('adress', models.CharField(max_length=100)),
                ('phone', models.IntegerField(default=1)),
                ('email', models.EmailField(max_length=254)),
                ('facebook', models.URLField()),
                ('youtube', models.URLField()),
                ('linkedin', models.URLField()),
                ('twitter', models.URLField()),
                ('pinterest', models.URLField(default='pita')),
            ],
            options={
                'verbose_name': 'Settings',
                'verbose_name_plural': 'Settings',
            },
        ),
    ]
