# Generated by Django 4.2.1 on 2023-05-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_settings_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='instagram',
            field=models.URLField(default='https://www.instagram.com/'),
        ),
    ]
