# Generated by Django 4.2.1 on 2023-05-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_settings_instagram'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Site Settings', 'verbose_name_plural': 'Site Settings'},
        ),
        migrations.AlterField(
            model_name='settings',
            name='instagram',
            field=models.URLField(),
        ),
    ]
