# Generated by Django 4.2.1 on 2023-05-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_settings_options_alter_settings_instagram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='pinterest',
            field=models.URLField(),
        ),
    ]
