# Generated by Django 4.2.1 on 2023-05-13 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_settings_pinterest'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowItWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('content', models.TextField(blank=True, verbose_name='Content')),
            ],
            options={
                'verbose_name': 'HowItWorks',
                'verbose_name_plural': 'HowItWorks',
            },
        ),
        migrations.CreateModel(
            name='HowItWorksPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('content', models.TextField(blank=True, verbose_name='Content')),
                ('howitworks', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hiw_points', to='core.howitworks')),
            ],
            options={
                'verbose_name': 'HowItWorksPoint',
                'verbose_name_plural': 'HowItWorksPoint',
            },
        ),
    ]
