# Generated by Django 4.2.1 on 2023-05-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_howitworks_howitworkspoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Title')),
                ('content', models.TextField(blank=True, verbose_name='Content')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('button1', models.CharField(max_length=15, verbose_name='Button1')),
                ('button2', models.CharField(max_length=15, verbose_name='Button2')),
                ('submit', models.CharField(max_length=15, verbose_name='Submit')),
            ],
            options={
                'verbose_name': 'NewsLetters',
                'verbose_name_plural': 'NewsLetters',
            },
        ),
    ]
