# Generated by Django 4.2.1 on 2023-05-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_settings_rights'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='rights',
        ),
        migrations.AddField(
            model_name='settings',
            name='year',
            field=models.CharField(default='', max_length=10),
        ),
    ]
