# Generated by Django 4.2.1 on 2023-05-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_settings_rights_settings_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='worktime',
            field=models.CharField(default='', max_length=25),
        ),
    ]
