# Generated by Django 4.2.1 on 2023-05-13 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_settings_worktime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GetInTouchPoint',
        ),
    ]
