# Generated by Django 4.2.1 on 2023-05-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_blogauthor_alter_settings_adress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=70, verbose_name='Title'),
        ),
    ]
