# Generated by Django 4.2.1 on 2023-05-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_blog_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='published_at',
            field=models.DateField(verbose_name='Published_at'),
        ),
    ]
