# Generated by Django 4.2.1 on 2023-05-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_settings_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='phone',
            field=models.CharField(max_length=15, null=True, verbose_name='Phone'),
        ),
    ]
